apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-qxat
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hnep-tenant/rhtap-demo-app/hacbs-test-project-qxat@sha256:f817bbe3cd669e79e24a43cf22109ff08a91a2dfbda78cb23594fe07cc615a0e
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
