apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-qxat
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hnep-tenant/rhtap-demo-app/hacbs-test-project-qxat@sha256:6536fcf1839e5e3b70061113a0364b8ac2d86a33f95ed55863984dcd4fde6700
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
